version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodbx
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
